Remove player from game and queue if they are moved to spectator
B3none/cs2-retakes pull request #126
Opened 2024-05-19 16:16 UTC by dollannn

I made these changes to ensure it is compatible with a plugin such as [AFKManager](https://github.com/NiGHT757/AFKManager) which only moves a player to spectator and has no way of knowing how to dequeue a player. Without this change players will be moved to spectator and then moved back into a team and actually never get kicked if you do not use an overly aggressive afk kick of 15 seconds without spectator. I made this for personal use but thought it might be benefit others

2024-05-19 16:32 UTC, B3none commented
These changes look great, are you able to move this logic into the relevant manager, I think I have separate team management logic in one of those where this code should be. If it can’t go there and it must go here then we can, I would also like to add a config option to give people the choice for how they would like to handle this. Basically just put it in an if statement with a config variable check.

2024-05-19 20:32 UTC, dollannn commented
Hope this resolves your comment, was unsure where to place the function but currently I put it in the GameManager class as it best fits there.

2024-05-19 21:46 UTC, B3none requested changes
Some minor tweaks, once those are addressed I'll make a release. Also please bump the plugin version const to `2.0.3` in `RetakesPlugin.cs`

2024-05-19 21:46 UTC, B3none commented on README.md
> +
Revert this additional line, and others formatting changes to the README

2024-05-19 21:46 UTC, B3none commented on RetakesPlugin/Modules/Managers/GameManager.cs
> +    private readonly bool _RemoveSpectatorsEnabled;
Rename this variable to `_removeSpectatorsEnabled`

2024-05-19 21:46 UTC, B3none commented on RetakesPlugin/Modules/Managers/GameManager.cs
> +using Serilog.Debugging;
Remove this, and it's usages

2024-05-19 21:46 UTC, B3none commented on RetakesPlugin/Modules/Configs/RetakesConfigData.cs
> +
Remove the additional extra line

2024-05-19 21:46 UTC, B3none commented on RetakesPlugin/Modules/Managers/GameManager.cs
> +        _RemoveSpectatorsEnabled = RemoveSpectatorsEnabled ?? true;
You need to default this behaviour to false, as that's how it was before and I want to maintain backwards compatibility / not introduce a potentially breaking change to peoples servers.

2024-05-19 21:46 UTC, B3none commented on README.md
> +| RemoveSpectators                                 | When a player is moved to spectators, remove them from all retake queues. Ensures that AFK plugins work as expected.
Default the value to false

2024-05-19 21:46 UTC, B3none commented on RetakesPlugin/Modules/Configs/RetakesConfigData.cs
> +    public bool RemoveSpectators { get; set; } = true;
Default this value to false, also as it's a boolean it needs to be prefixed with `Is` / `Has` / `Should` / `Enable`

2024-05-19 21:46 UTC, B3none commented on RetakesPlugin/RetakesPlugin.cs
> +        return _gameManager.RemoveSpectators(@event, _hasMutedVoices);
Add an empty line above this return statement

2024-05-19 22:15 UTC, dollannn commented
Bumped to 2.0.5 instead of 2.0.3 as we are on 2.0.4

2024-05-19 23:11 UTC, B3none requested changes
Well spotted with the version, two minor tweaks and it’s good to merge.

2024-05-19 23:11 UTC, B3none commented on README.md
> +| RemoveSpectators                                  | When a player is moved to spectators, remove them from all retake queues. Ensures that AFK plugins work as expected.                            |
Update the name of the variable in the readme

2024-05-19 23:11 UTC, B3none commented on README.md
> +This was inspired by the [CS:GO Retakes project](https://github.com/splewis/csgo-retakes) written by [splewis](https://github.com/splewis).
Remove this formatting change

2024-05-20 11:28 UTC, B3none approved these changes

2024-05-20 12:07 UTC, merged